// 项目根 build.gradle
buildscript {
    ext {
        tinkerVersion = "1.9.15.2"
        compileSdkVersion = 33
        minSdkVersion = 19
        targetSdkVersion = 33
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        // Tinker Gradle 插件
        classpath "com.tencent.tinker:tinker-patch-gradle-plugin:${tinkerVersion}"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
